# Generated by Django 6.1.1 on 2026-09-21 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drivers.driverprofile'),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['status'], name='drivers_dri_status_1fdaae_idx'),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['verification_status'], name='drivers_dri_verific_221907_idx'),
        ),
        migrations.AddIndex(
            model_name='driverdocument',
            index=models.Index(fields=['driver'], name='drivers_dri_driver__28bb40_idx'),
        ),
        migrations.AddIndex(
            model_name='driverdocument',
            index=models.Index(fields=['status'], name='drivers_dri_status_7096f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='driverdocument',
            constraint=models.UniqueConstraint(fields=('driver', 'document_type'), name='unique_document_per_type'),
        ),
    ]
