# Generated by Django 6.1.1 on 2026-09-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdocument',
            name='rejection_reason_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='rejection_reason_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_number_en',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_number_fr',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
