# Generated by Django 6.1.1 on 2026-09-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driverdocument_rejection_reason_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdocument',
            name='rejection_reason_hi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_number_hi',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
