# Generated by Django 6.1.1 on 2026-09-25 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driverdocument_rejection_reason_hi_and_more'),
        ('rides', '0006_ride_arrived_at_ride_completed_at_ride_driver_payout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='drivers.driverprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('reason', models.CharField(choices=[('RIDE_EARNING', 'Ride Earning'), ('ADJUSTMENT', 'Manual Adjustment'), ('WITHDRAWAL', 'Withdrawal')], default='RIDE_EARNING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='rides.ride')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='drivers.driverwallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='drivers_wal_wallet__ec8c1c_idx')],
            },
        ),
    ]
