# Generated by Django 6.1.1 on 2026-10-06 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_driverwallet_wallettransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='drivers.driverprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['driver', 'started_at'], name='drivers_dri_driver__d06d42_idx')],
            },
        ),
    ]
