# Generated by Django 6.1.1 on 2026-10-09 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_driversession'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversession',
            name='last_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='driversession',
            index=models.Index(fields=['ended_at', 'last_seen_at'], name='drivers_dri_ended_a_4313fb_idx'),
        ),
    ]
