# Generated by Django 6.1.1 on 2026-09-24 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0004_driverdocument_rejection_reason_hi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('AUTO', 'Auto')], max_length=10, verbose_name='vehicle type')),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='pickup latitude')),
                ('pickup_lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='pickup longitude')),
                ('pickup_address', models.CharField(max_length=255, verbose_name='pickup address')),
                ('drop_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='drop latitude')),
                ('drop_lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='drop longitude')),
                ('drop_address', models.CharField(max_length=255, verbose_name='drop address')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='distance (km)')),
                ('estimated_fare', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='estimated fare')),
                ('status', models.CharField(choices=[('SEARCHING', 'Searching'), ('ACCEPTED', 'Accepted'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SEARCHING', max_length=20, verbose_name='status')),
                ('cancelled_by', models.CharField(blank=True, choices=[('RIDER', 'Rider'), ('DRIVER', 'Driver')], max_length=10, verbose_name='cancelled by')),
                ('cancel_reason', models.CharField(blank=True, max_length=255, verbose_name='cancel reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rides', to='drivers.driverprofile', verbose_name='driver')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL, verbose_name='rider')),
            ],
            options={
                'verbose_name': 'Ride',
                'verbose_name_plural': 'Rides',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rider', 'status'], name='rides_ride_rider_i_bc1d57_idx'), models.Index(fields=['status'], name='rides_ride_status_b1560e_idx')],
            },
        ),
    ]
