# Generated by Django 6.1.1 on 2026-09-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='notified_driver_user_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='notified driver user ids'),
        ),
    ]
