# Generated by Django 6.1.1 on 2026-09-24 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driverdocument_rejection_reason_hi_and_more'),
        ('rides', '0002_ride_notified_driver_user_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='SENT', max_length=10, verbose_name='status')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_offers', to='drivers.driverprofile', verbose_name='driver')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='rides.ride', verbose_name='ride')),
            ],
            options={
                'verbose_name': 'Ride Offer',
                'verbose_name_plural': 'Ride Offers',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['ride', 'status'], name='rides_rideo_ride_id_fbae44_idx'), models.Index(fields=['driver', 'status'], name='rides_rideo_driver__3b726e_idx')],
                'constraints': [models.UniqueConstraint(fields=('ride', 'driver'), name='unique_ride_offer_per_driver')],
            },
        ),
    ]
