# Generated by Django 6.1.1 on 2026-09-25 06:04

import rides.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_rideoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='final_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='final fare'),
        ),
        migrations.AddField(
            model_name='ride',
            name='otp',
            field=models.CharField(default=rides.models.generate_otp, max_length=4, verbose_name='start trip otp'),
        ),
        migrations.AddField(
            model_name='ride',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash')], default='CASH', max_length=10, verbose_name='payment method'),
        ),
        migrations.AddField(
            model_name='ride',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=10, verbose_name='payment status'),
        ),
    ]
