# Generated by Django 6.1.1 on 2026-09-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_ride_final_fare_ride_otp_ride_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('MOBILE_MONEY', 'Mobile Money')], default='CASH', max_length=15, verbose_name='payment method'),
        ),
    ]
