# Generated by Django 6.1.1 on 2026-09-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_alter_ride_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='driver arrived at'),
        ),
        migrations.AddField(
            model_name='ride',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='trip completed at'),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='driver payout (locked at booking time)'),
        ),
        migrations.AddField(
            model_name='ride',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='trip started at'),
        ),
    ]
