# Generated by Django 6.1.1 on 2026-10-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review_en',
            field=models.TextField(blank=True, null=True, verbose_name='review'),
        ),
        migrations.AddField(
            model_name='rating',
            name='review_fr',
            field=models.TextField(blank=True, null=True, verbose_name='review'),
        ),
        migrations.AddField(
            model_name='rating',
            name='review_hi',
            field=models.TextField(blank=True, null=True, verbose_name='review'),
        ),
        migrations.AddField(
            model_name='ride',
            name='cancel_reason_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cancel reason'),
        ),
        migrations.AddField(
            model_name='ride',
            name='cancel_reason_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cancel reason'),
        ),
        migrations.AddField(
            model_name='ride',
            name='cancel_reason_hi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cancel reason'),
        ),
        migrations.AddField(
            model_name='ride',
            name='drop_address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='drop address'),
        ),
        migrations.AddField(
            model_name='ride',
            name='drop_address_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='drop address'),
        ),
        migrations.AddField(
            model_name='ride',
            name='drop_address_hi',
            field=models.CharField(max_length=255, null=True, verbose_name='drop address'),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='pickup address'),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_address_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='pickup address'),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_address_hi',
            field=models.CharField(max_length=255, null=True, verbose_name='pickup address'),
        ),
    ]
