# Generated by Django 6.1.1 on 2026-10-10 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_driversession_last_seen_at_and_more'),
        ('rides', '0008_rating_review_en_rating_review_fr_rating_review_hi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='payment_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='payment details'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', 'created_at'], name='rides_ride_status_9f4eb8_idx'),
        ),
    ]
