# Generated by Django 6.1.1 on 2026-09-22 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RC', 'Registration Certificate'), ('INSURANCE', 'Insurance'), ('PUC', 'Pollution Certificate'), ('PERMIT', 'Permit')], max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('document_file', models.FileField(upload_to='vehicle_documents/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='vehicle',
            name='vehicles_ve_driver__4d0206_idx',
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_active'], name='vehicles_ve_is_acti_53dbe5_idx'),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle'),
        ),
        migrations.AddIndex(
            model_name='vehicledocument',
            index=models.Index(fields=['verification_status'], name='vehicles_ve_verific_450550_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledocument',
            index=models.Index(fields=['expiry_date'], name='vehicles_ve_expiry__3f4876_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicledocument',
            constraint=models.UniqueConstraint(fields=('vehicle', 'document_type'), name='unique_vehicle_document_type'),
        ),
    ]
