# Generated by Django 6.1.1 on 2026-09-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicledocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color_fr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_number_en',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_number_fr',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='document_number_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='document_number_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='rejection_reason_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='rejection_reason_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
