# Generated by Django 6.1.1 on 2026-09-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_color_en_vehicle_color_fr_vehicle_make_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color_hi',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make_hi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_hi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_number_hi',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='document_number_hi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='rejection_reason_hi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
