# Generated by Django 6.1.1 on 2026-09-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_color_hi_vehicle_make_hi_vehicle_model_hi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('AUTO', 'Auto')], max_length=10, unique=True)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=6)),
                ('per_km_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('minimum_fare', models.DecimalField(decimal_places=2, max_digits=6)),
                ('platform_commission_percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('night_pricing_enabled', models.BooleanField(default=False)),
                ('night_start_hour', models.PositiveSmallIntegerField(default=23)),
                ('night_end_hour', models.PositiveSmallIntegerField(default=5)),
                ('night_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Pricing',
                'verbose_name_plural': 'Vehicle Pricing',
            },
        ),
    ]
