# Generated by Django 6.1.1 on 2026-10-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehiclepricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclepricing',
            name='platform_commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
